AnimationPointers2:
	dw TreeckoAnimation
	dw GrovyleAnimation
	dw SceptileAnimation
	dw TorchicAnimation
	dw CombuskenAnimation
	dw BlazikenAnimation
	dw MudkipAnimation
	dw MarshtompAnimation
	dw SwampertAnimation
	dw PoochyenaAnimation
	dw MightyenaAnimation
	dw ZigzagoonAnimation
	dw LinooneAnimation
	dw WurmpleAnimation
	dw SilcoonAnimation
	dw BeautiflyAnimation
	dw CascoonAnimation
	dw DustoxAnimation
	dw LotadAnimation
	dw LombreAnimation
	dw LudicoloAnimation
	dw SeedotAnimation
	dw NuzleafAnimation
	dw ShiftryAnimation
	dw TaillowAnimation
	dw SwellowAnimation
	dw WingullAnimation
	dw PelipperAnimation
	dw RaltsAnimation
	dw KirliaAnimation
	dw GardevoirAnimation
	dw SurskitAnimation
	dw MasquerainAnimation
	dw ShroomishAnimation
	dw BreloomAnimation
	dw SlakothAnimation
	dw VigorothAnimation
	dw SlakingAnimation
	dw NincadaAnimation
	dw NinjaskAnimation
	dw ShedinjaAnimation
	dw WhismurAnimation
	dw LoudredAnimation
	dw ExploudAnimation
	dw MakuhitaAnimation
	dw HariyamaAnimation
	dw AzurillAnimation
	dw NosepassAnimation
	dw SkittyAnimation
	dw DelcattyAnimation
	dw SableyeAnimation
	dw MawileAnimation
	dw AronAnimation
	dw LaironAnimation
	dw AggronAnimation
	dw MedititeAnimation
	dw MedichamAnimation
	dw ElectrikeAnimation
	dw ManectricAnimation
	dw PlusleAnimation
	dw MinunAnimation
	dw VolbeatAnimation
	dw IllumiseAnimation
	dw RoseliaAnimation
	dw GulpinAnimation
	dw SwalotAnimation
	dw CarvanhaAnimation
	dw SharpedoAnimation
	dw WailmerAnimation
	dw WailordAnimation
	dw NumelAnimation
	dw CameruptAnimation
	dw TorkoalAnimation
	dw SpoinkAnimation
	dw GrumpigAnimation
	dw SpindaAnimation
	dw TrapinchAnimation
	dw VibravaAnimation
	dw FlygonAnimation
	dw CacneaAnimation
	dw CacturneAnimation
	dw SwabluAnimation
	dw AltariaAnimation
	dw ZangooseAnimation
	dw SeviperAnimation
	dw LunatoneAnimation
	dw SolrockAnimation
	dw BarboachAnimation
	dw WhiscashAnimation
	dw CorphishAnimation
	dw CrawdauntAnimation
	dw BaltoyAnimation
	dw ClaydolAnimation
	dw LileepAnimation
	dw CradilyAnimation
	dw AnorithAnimation
	dw ArmaldoAnimation
	dw FeebasAnimation
	dw MiloticAnimation
	dw CastformAnimation
	dw KecleonAnimation
	dw ShuppetAnimation
	dw BanetteAnimation
	dw DuskullAnimation
	dw DusclopsAnimation
	dw TropiusAnimation
	dw ChimechoAnimation
	dw AbsolAnimation
	dw WynautAnimation
	dw SnoruntAnimation
	dw GlalieAnimation
	dw SphealAnimation
	dw SealeoAnimation
	dw WalreinAnimation
	dw ClamperlAnimation
	dw HuntailAnimation
	dw GorebyssAnimation
	dw RelicanthAnimation
	dw LuvdiscAnimation
	dw BagonAnimation
	dw ShelgonAnimation
	dw SalamenceAnimation
	dw BeldumAnimation
	dw MetangAnimation
	dw MetagrossAnimation
	dw RegirockAnimation
	dw RegiceAnimation
	dw RegisteelAnimation
	dw LatiasAnimation
	dw LatiosAnimation
	dw KyogreAnimation
	dw GroudonAnimation
	dw RayquazaAnimation
	dw JirachiAnimation
	dw DeoxysAnimation
	dw TurtwigAnimation
	dw GrotleAnimation
	dw TorterraAnimation
	dw ChimcharAnimation
	dw MonfernoAnimation
	dw InfernapeAnimation
	dw PiplupAnimation
	dw PrinplupAnimation
	dw EmpoleonAnimation
	dw StarlyAnimation
	dw StaraviaAnimation
	dw StaraptorAnimation
	dw BidoofAnimation
	dw BibarelAnimation
	dw KricketotAnimation
	dw KricketuneAnimation
	dw ShinxAnimation
	dw LuxioAnimation
	dw LuxrayAnimation
	dw BudewAnimation
	dw RoseradeAnimation
	dw CranidosAnimation
	dw RampardosAnimation
	dw ShieldonAnimation
	dw BastiodonAnimation
	dw BurmyAnimation
	dw WormadamAnimation
	dw MothimAnimation
	dw CombeeAnimation
	dw VespiquenAnimation
	dw PachirisuAnimation
	dw BuizelAnimation
	dw FloatzelAnimation
	dw CherubiAnimation
	dw CherrimAnimation
	dw ShellosAnimation
	dw GastrodonAnimation
	dw AmbipomAnimation
	dw DrifloonAnimation
	dw DrifblimAnimation
	dw BunearyAnimation
	dw LopunnyAnimation
	dw MismagiusAnimation
	dw HonchkrowAnimation
	dw GlameowAnimation
	dw PuruglyAnimation
	dw ChinglingAnimation
	dw StunkyAnimation
	dw SkuntankAnimation
	dw BronzorAnimation
	dw BronzongAnimation
	dw BonslyAnimation
	dw MimeJrAnimation
	dw HappinyAnimation
	dw ChatotAnimation
	dw SpiritombAnimation
	dw GibleAnimation
	dw GabiteAnimation
	dw GarchompAnimation
	dw MunchlaxAnimation
	dw RioluAnimation
	dw LucarioAnimation
	dw HippopotasAnimation
	dw HippowdonAnimation
	dw SkorupiAnimation
	dw DrapionAnimation
	dw CroagunkAnimation
	dw ToxicroakAnimation
	dw CarnivineAnimation
	dw FinneonAnimation
	dw LumineonAnimation
	dw MantykeAnimation
	dw SnoverAnimation
	dw AbomasnowAnimation
	dw WeavileAnimation
	dw MagnezoneAnimation
	dw LickilickyAnimation
	dw RhyperiorAnimation
	dw TangrowthAnimation
	dw ElectivireAnimation
	dw MagmortarAnimation
	dw TogekissAnimation
	dw YanmegaAnimation
	dw LeafeonAnimation
	dw GlaceonAnimation
	dw GliscorAnimation
	dw MamoswineAnimation
	dw PorygonZAnimation
	dw GalladeAnimation
	dw ProbopassAnimation
	dw DusknoirAnimation
	dw FroslassAnimation
	dw RotomAnimation
	dw UxieAnimation
	dw MespritAnimation
	dw AzelfAnimation
	dw DialgaAnimation
	dw PalkiaAnimation
	dw HeatranAnimation
	dw RegigigasAnimation
	dw GiratinaAnimation
	dw CresseliaAnimation
	dw PhioneAnimation
	dw ManaphyAnimation
	dw DarkraiAnimation
	dw ShayminAnimation
	dw ArceusAnimation
	dw SylveonAnimation
	dw RegielekiAnimation
	dw RegidragoAnimation
