AnimationIdlePointers2:
	dw TreeckoAnimationIdle
	dw GrovyleAnimationIdle
	dw SceptileAnimationIdle
	dw TorchicAnimationIdle
	dw CombuskenAnimationIdle
	dw BlazikenAnimationIdle
	dw MudkipAnimationIdle
	dw MarshtompAnimationIdle
	dw SwampertAnimationIdle
	dw PoochyenaAnimationIdle
	dw MightyenaAnimationIdle
	dw ZigzagoonAnimationIdle
	dw LinooneAnimationIdle
	dw WurmpleAnimationIdle
	dw SilcoonAnimationIdle
	dw BeautiflyAnimationIdle
	dw CascoonAnimationIdle
	dw DustoxAnimationIdle
	dw LotadAnimationIdle
	dw LombreAnimationIdle
	dw LudicoloAnimationIdle
	dw SeedotAnimationIdle
	dw NuzleafAnimationIdle
	dw ShiftryAnimationIdle
	dw TaillowAnimationIdle
	dw SwellowAnimationIdle
	dw WingullAnimationIdle
	dw PelipperAnimationIdle
	dw RaltsAnimationIdle
	dw KirliaAnimationIdle
	dw GardevoirAnimationIdle
	dw SurskitAnimationIdle
	dw MasquerainAnimationIdle
	dw ShroomishAnimationIdle
	dw BreloomAnimationIdle
	dw SlakothAnimationIdle
	dw VigorothAnimationIdle
	dw SlakingAnimationIdle
	dw NincadaAnimationIdle
	dw NinjaskAnimationIdle
	dw ShedinjaAnimationIdle
	dw WhismurAnimationIdle
	dw LoudredAnimationIdle
	dw ExploudAnimationIdle
	dw MakuhitaAnimationIdle
	dw HariyamaAnimationIdle
	dw AzurillAnimationIdle
	dw NosepassAnimationIdle
	dw SkittyAnimationIdle
	dw DelcattyAnimationIdle
	dw SableyeAnimationIdle
	dw MawileAnimationIdle
	dw AronAnimationIdle
	dw LaironAnimationIdle
	dw AggronAnimationIdle
	dw MedititeAnimationIdle
	dw MedichamAnimationIdle
	dw ElectrikeAnimationIdle
	dw ManectricAnimationIdle
	dw PlusleAnimationIdle
	dw MinunAnimationIdle
	dw VolbeatAnimationIdle
	dw IllumiseAnimationIdle
	dw RoseliaAnimationIdle
	dw GulpinAnimationIdle
	dw SwalotAnimationIdle
	dw CarvanhaAnimationIdle
	dw SharpedoAnimationIdle
	dw WailmerAnimationIdle
	dw WailordAnimationIdle
	dw NumelAnimationIdle
	dw CameruptAnimationIdle
	dw TorkoalAnimationIdle
	dw SpoinkAnimationIdle
	dw GrumpigAnimationIdle
	dw SpindaAnimationIdle
	dw TrapinchAnimationIdle
	dw VibravaAnimationIdle
	dw FlygonAnimationIdle
	dw CacneaAnimationIdle
	dw CacturneAnimationIdle
	dw SwabluAnimationIdle
	dw AltariaAnimationIdle
	dw ZangooseAnimationIdle
	dw SeviperAnimationIdle
	dw LunatoneAnimationIdle
	dw SolrockAnimationIdle
	dw BarboachAnimationIdle
	dw WhiscashAnimationIdle
	dw CorphishAnimationIdle
	dw CrawdauntAnimationIdle
	dw BaltoyAnimationIdle
	dw ClaydolAnimationIdle
	dw LileepAnimationIdle
	dw CradilyAnimationIdle
	dw AnorithAnimationIdle
	dw ArmaldoAnimationIdle
	dw FeebasAnimationIdle
	dw MiloticAnimationIdle
	dw CastformAnimationIdle
	dw KecleonAnimationIdle
	dw ShuppetAnimationIdle
	dw BanetteAnimationIdle
	dw DuskullAnimationIdle
	dw DusclopsAnimationIdle
	dw TropiusAnimationIdle
	dw ChimechoAnimationIdle
	dw AbsolAnimationIdle
	dw WynautAnimationIdle
	dw SnoruntAnimationIdle
	dw GlalieAnimationIdle
	dw SphealAnimationIdle
	dw SealeoAnimationIdle
	dw WalreinAnimationIdle
	dw ClamperlAnimationIdle
	dw HuntailAnimationIdle
	dw GorebyssAnimationIdle
	dw RelicanthAnimationIdle
	dw LuvdiscAnimationIdle
	dw BagonAnimationIdle
	dw ShelgonAnimationIdle
	dw SalamenceAnimationIdle
	dw BeldumAnimationIdle
	dw MetangAnimationIdle
	dw MetagrossAnimationIdle
	dw RegirockAnimationIdle
	dw RegiceAnimationIdle
	dw RegisteelAnimationIdle
	dw LatiasAnimationIdle
	dw LatiosAnimationIdle
	dw KyogreAnimationIdle
	dw GroudonAnimationIdle
	dw RayquazaAnimationIdle
	dw JirachiAnimationIdle
	dw DeoxysAnimationIdle
	dw TurtwigAnimationIdle
	dw GrotleAnimationIdle
	dw TorterraAnimationIdle
	dw ChimcharAnimationIdle
	dw MonfernoAnimationIdle
	dw InfernapeAnimationIdle
	dw PiplupAnimationIdle
	dw PrinplupAnimationIdle
	dw EmpoleonAnimationIdle
	dw StarlyAnimationIdle
	dw StaraviaAnimationIdle
	dw StaraptorAnimationIdle
	dw BidoofAnimationIdle
	dw BibarelAnimationIdle
	dw KricketotAnimationIdle
	dw KricketuneAnimationIdle
	dw ShinxAnimationIdle
	dw LuxioAnimationIdle
	dw LuxrayAnimationIdle
	dw BudewAnimationIdle
	dw RoseradeAnimationIdle
	dw CranidosAnimationIdle
	dw RampardosAnimationIdle
	dw ShieldonAnimationIdle
	dw BastiodonAnimationIdle
	dw BurmyAnimationIdle
	dw WormadamAnimationIdle
	dw MothimAnimationIdle
	dw CombeeAnimationIdle
	dw VespiquenAnimationIdle
	dw PachirisuAnimationIdle
	dw BuizelAnimationIdle
	dw FloatzelAnimationIdle
	dw CherubiAnimationIdle
	dw CherrimAnimationIdle
	dw ShellosAnimationIdle
	dw GastrodonAnimationIdle
	dw AmbipomAnimationIdle
	dw DrifloonAnimationIdle
	dw DrifblimAnimationIdle
	dw BunearyAnimationIdle
	dw LopunnyAnimationIdle
	dw MismagiusAnimationIdle
	dw HonchkrowAnimationIdle
	dw GlameowAnimationIdle
	dw PuruglyAnimationIdle
	dw ChinglingAnimationIdle
	dw StunkyAnimationIdle
	dw SkuntankAnimationIdle
	dw BronzorAnimationIdle
	dw BronzongAnimationIdle
	dw BonslyAnimationIdle
	dw MimeJrAnimationIdle
	dw HappinyAnimationIdle
	dw ChatotAnimationIdle
	dw SpiritombAnimationIdle
	dw GibleAnimationIdle
	dw GabiteAnimationIdle
	dw GarchompAnimationIdle
	dw MunchlaxAnimationIdle
	dw RioluAnimationIdle
	dw LucarioAnimationIdle
	dw HippopotasAnimationIdle
	dw HippowdonAnimationIdle
	dw SkorupiAnimationIdle
	dw DrapionAnimationIdle
	dw CroagunkAnimationIdle
	dw ToxicroakAnimationIdle
	dw CarnivineAnimationIdle
	dw FinneonAnimationIdle
	dw LumineonAnimationIdle
	dw MantykeAnimationIdle
	dw SnoverAnimationIdle
	dw AbomasnowAnimationIdle
	dw WeavileAnimationIdle
	dw MagnezoneAnimationIdle
	dw LickilickyAnimationIdle
	dw RhyperiorAnimationIdle
	dw TangrowthAnimationIdle
	dw ElectivireAnimationIdle
	dw MagmortarAnimationIdle
	dw TogekissAnimationIdle
	dw YanmegaAnimationIdle
	dw LeafeonAnimationIdle
	dw GlaceonAnimationIdle
	dw GliscorAnimationIdle
	dw MamoswineAnimationIdle
	dw PorygonZAnimationIdle
	dw GalladeAnimationIdle
	dw ProbopassAnimationIdle
	dw DusknoirAnimationIdle
	dw FroslassAnimationIdle
	dw RotomAnimationIdle
	dw UxieAnimationIdle
	dw MespritAnimationIdle
	dw AzelfAnimationIdle
	dw DialgaAnimationIdle
	dw PalkiaAnimationIdle
	dw HeatranAnimationIdle
	dw RegigigasAnimationIdle
	dw GiratinaAnimationIdle
	dw CresseliaAnimationIdle
	dw PhioneAnimationIdle
	dw ManaphyAnimationIdle
	dw DarkraiAnimationIdle
	dw ShayminAnimationIdle
	dw ArceusAnimationIdle
	dw SylveonAnimationIdle
	dw RegielekiAnimationIdle
	dw RegidragoAnimationIdle
